version: '3.8'

services:
  traefik:
    image: traefik:v2.6
    container_name: traefik
    command:
      - "--api.insecure=false"  # Disable insecure Traefik dashboard
      - "--providers.docker=true"  # Enable Docker provider
      - "--entrypoints.web.address=:80"  # Expose HTTP port
      - "--entrypoints.websecure.address=:443"  # Expose HTTPS port
      - "--certificatesresolvers.myresolver.acme.httpChallenge=true"  # Add this line
      - "--certificatesresolvers.myresolver.acme.httpChallenge.entryPoint=web"  # Add this line
      - "--certificatesresolvers.myresolver.acme.email=support@codemelon.xyz"  # Set your actual email for Let's Encrypt
      - "--certificatesresolvers.myresolver.acme.storage=/acme.json"  # Store certs
      - "--entrypoints.websecure.http.tls=true"  # Enable TLS on websecure
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"  # Existing volume mapping
      - "./letsencrypt/acme.json:/acme.json" 
      # - "letsencrypt:/letsencrypt"
      # - "./traefik/traefik.yml:/traefik.yml"

  codemelon-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: codemelon-backend:latest
    container_name: codemelon-app
    env_file:
      - .env
    labels:
    - "traefik.enable=true"  # Enable Traefik for this service
    - "traefik.http.routers.codemelon-app.rule=Host(`ai.api.codemelon.xyz`)"  # Route based on the host
    - "traefik.http.routers.codemelon-app.entrypoints=websecure"  # Use HTTPS (websecure)
    - "traefik.http.routers.codemelon-app.tls.certresolver=myresolver"  # Use the defined certificate resolver
    - "traefik.http.services.codemelon-app.loadbalancer.server.port=8000"  # Route to backend on port 8000
    - "traefik.http.routers.codemelon-app-http.rule=Host(`ai.api.codemelon.xyz`)"  # HTTP router rule
    - "traefik.http.routers.codemelon-app-http.entrypoints=web"  # HTTP entrypoint
    - "traefik.http.routers.codemelon-app-http.middlewares=redirect-to-https"  # Redirect middleware
    - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"  # Redirect to HTTPS
    restart: unless-stopped
    ports:
      - "8000:8000"  # Expose internal port for app container (not necessary for Traefik, but useful for debugging)