version: '3.8'

services:
  traefik:
    image: traefik:v2.6
    container_name: traefik
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlsChallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=support@codemelon.xyz"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "letsencrypt:/letsencrypt"
      - "./letsencrypt/acme.json:/letsencrypt/acme.json"

  codemelon-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: codemelon-backend:latest
    container_name: codemelon-app
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.codemelon-app.rule=Host(`34.0.7.222`)"
      - "traefik.http.routers.codemelon-app.entrypoints=web"
      - "traefik.http.routers.codemelon-app-secure.rule=Host(`34.0.7.222`)"
      - "traefik.http.routers.codemelon-app-secure.entrypoints=websecure"
      - "traefik.http.routers.codemelon-app-secure.tls.certresolver=myresolver"
      - "traefik.http.routers.codemelon-app-ai.rule=Host(`ai.api.codemelon.xyz`)"
      - "traefik.http.routers.codemelon-app-ai.entrypoints=web"
      - "traefik.http.routers.codemelon-app-ai-secure.rule=Host(`ai.api.codemelon.xyz`)"
      - "traefik.http.routers.codemelon-app-ai-secure.entrypoints=websecure"
      - "traefik.http.routers.codemelon-app-ai-secure.tls.certresolver=myresolver"
    environment:
      - PORT=8000

volumes:
  letsencrypt: